### ISSUE TITLE
Should we consider EINTR

### ISSUE THREAD

**Issue by ampresent** [chrisjbillington/inotify_simple#10]
https://github.com/chrisjbillington/inotify_simple/blob/f7e99db29cb4365137ca1326c14365bcc5c30741/inotify_simple/inotify_simple.py#L136

When poll is interrupted, should inotify_simple do it again, or should the library user do it again ?

**Comment by chrisjbillington** [comment]
It is a good point, since we are considering EINTR in the libc calls. However, since Python 3.5, system calls are already retried upon EINTR due to the implementation of [PEP 475](https://www.python.org/dev/peps/pep-0475/), so accounting for it in the `poll()` call would be only useful for older Python versions. And, to be strictly correct, we would need to recompute the timeout upon each EINTR, and we don't even have a monotonic clock with which to reliably do this in Python 2. The `time.sleep(read_delay/1000)` could also return early due to EINTR, however, if I understand correctly, in Python < 3.5 the caller doesn't get the exception in this case, they simply get a time.sleep() that returned early, with no way to tell. So we just can't get that correct. EINTR in Python < 3.5 is a bit of a mess.

For those reasons I think I'm leaning toward thanking our standard library overlords for handling this for us in Python 3.5+, and  letting users of older Pythons handle it themselves if they don't want to or can't use Python 3.5+. Users of older Python versions who care about this surely have a lot of other cases where they have to deal with EINTR in their code already, and inotify_simple looks well behaved enough if it raises EINTR from the `poll()`, it is not modifying any instance variables or anything and will be totally safe to just try again.

**Comment by ampresent** [comment]
Thank you so much for having me understood and learnt much related information!

I think I can close this issue now.
