### ISSUE TITLE
Strange exception during initalization 

### ISSUE THREAD

**Issue by letorbi** [chrisjbillington/inotify_simple#27]
Hello Chris,

one of the users of Synoindex Watcher has reported a strange exception (https://github.com/letorbi/synoindexwatcher/issues/48):

```
2021-05-04 08:46:08,811 ERROR An uncaught exception occurred
Traceback (most recent call last):
File "/lib/python2.7/site-packages/synoindexwatcher/main.py", line 218, in
start()
File "/lib/python2.7/site-packages/synoindexwatcher/main.py", line 183, in start
inotify = INotify()
File "/usr/lib/python2.7/site-packages/inotifyrecursive/inotifyrecursive.py", line 31, in init
inotify_simple.INotify.init(self)
File "/usr/lib/python2.7/site-packages/inotify_simple.py", line 91, in init
FileIO.init(self, _libc_call(_libc.inotify_init1, flags), mode='rb')
IOError: [Errno 21] Is a directory: 3
```

Since *synoindexwatcher* just calls the `INotify()` constructor of *inotifyrecusive*, which then calls `inotify_simple.INotify.__init__(self)` in its first line, I assume the bug - if there is one - lies within *inotify_simple*.

I've looked at your code, but was not able to fully understand what line 91 does. Could you explain it to me and do you have an idea what could be the problem and how to fix it?

Regards,
Torben

**Comment by chrisjbillington** [comment]
I think this is the same issue: https://github.com/chrisjbillington/inotify_simple/issues/17

The latest version of `inotify_simple` doesn't support a kernel as old as the one you're running, but version 1.2.1 does.

[`synoindexwatcher` depends on inotify_simple](https://github.com/letorbi/synoindexwatcher/blob/master/setup.py) via its dependence on `inotifyrecursive`, but if all synology devices it supports have a similarly old kernel, you might suggest to `synoindexwatcher` that they add `inotify_simple <= 1.2.1` to their requirements to cap the version of `inotify_simple` at the last compatible one. Or if they support multiple kernels, they could add this info to their README.

Supporting an older kernel unfortunately compromises on some of the design decisions in `inotify_simple`, otherwise if it were simple I would just make whatever change was needed to support it.

**Comment by letorbi** [comment]
Thanks for your feedback. Since *synoindexwatcher* does not have this problem on recent versions of DSM (Synology's operating system), I assume that the user, who reported the issue, has an old DSM version. I'll tell him about the solutions you've suggested and might also add a FAQ entry.

Do you have an idea what minimum kernel version is required to use the current version of *inotify_simple*? I assume 4.x ..?

PS: I'm the developer of Synoindex Watcher ;) I was just asking for another user who reported the issue, but went silent afterwards.

**Comment by chrisjbillington** [comment]
I've tested that kernel 3.0.0 works, so I imagine anything from there up should be fine.

The previous bug report I got was on 2.6.32, so the fix that made the inotify filedescriptor not have the directory flag set must have been somewhere in between.

**Comment by letorbi** [comment]
Great, thanks for the info. I guess, that solves this issue :)

**Comment by chrisjbillington** [comment]
:)
