### ISSUE TITLE
Close in destructor?

### ISSUE THREAD

**Issue by fishermans-friend** [chrisjbillington/inotify_simple#28]
In the documentation it says "`close()` should be called when no longer needed.", presumably to avoid leaking file descriptors.

Is there any particular reason this can't be implemented in the `__del__` method of the class? It's safe to call `close()` on FileIO objects several times, so it shouldn't break any existing code. Am I missing something?

**Comment by chrisjbillington** [comment]
Since it's a subclass of `FileIO`, `close()` is already called as part of `FileIO`'s `__del__` method.

I verified this by adding the method:
```python
def close(self):
    print("close")
    super().close()
```
and then testing
```python
>>> x = INotify()
>>> del x
close
```

The documentation is typical of Python's documentation for things that need cleaning up, even if the cleanup is done automatically when the reference count reaches zero. Explicit is better than implicit! Context managers are the best of both worlds:
```python
>>> with INotify() as x:
...     print('hi')
...
hi
close
```
