### ISSUE TITLE
pathlib support

### ISSUE THREAD

**Issue by abjugard** [chrisjbillington/inotify_simple#3]
[pathlib](https://docs.python.org/3/library/pathlib.html) is the latest craze in the python world, and it would be great if inotify_simple accepted pathlib paths.

**Comment by chrisjbillington** [comment]
You can already pass in ``Path`` objects to ``INotify.add_watch()``, since ``Path`` objects have an ``encode()`` method returning ``bytes`` - which is all that ``INotify.add_watch()`` cares about. So that already works for anyone using ``Path`` objects.

The only other place a change would occur is in the ``Event`` objects - they would be changed to contain a ``Path`` object for the name instead of a string. I don't think this is the correct behaviour because the names coming from inotify are not actually paths - they're just a single name of an entry in a directory being watched. So constructing a full path would mean we would no longer be a literal wrapper of inotify. 

In any case, creating a full filepath would require knowing all the parent directories, which might not even be unambiguously knowable due to the existence of links, and would be difficult to construct due to race conditions. So any attempt at this would not live up to the 'simple' moniker in the package name.

But as I said, it's not the right behaviour anyway. The only non-racey way to know that name's parent directory is the watch descriptor that the event comes in on. Using full filepaths isn't the right approach when inotify is all about the fact that these things can change at a moment's notice. To get correct filepaths (where 'correct' means 'correct at the time of the last inotify event we processed') you would have to maintain all the filepaths in some datastructure, be watching every parent directory and responding to move events by recursively updating all the paths in the datastructure. It's tricky! And whilst that's one *application* of inotify, it's not what inotify itself does and so doesn't belong in this package.
